### ISSUE TITLE
Question on how to make a BaseController

### ISSUE THREAD

**Issue by meshileya** [davidseek/CustomPresentAndDismiss#1]
Hello @davidseek , thanks so much for this sample.

I will appreciate a guide on how to implement this flow in a base Controller that will affect every other UIViewController inheriting from the BaseController, please.

Instead of having to copy codes over all the controllers to be used, let's say i have 5 different Controllers in my project, is there a way i can implement this across all controllers without having to copy and paste the gesture/behavior across all the Controllers...don't know if you get that, pls.

**Comment by davidseek** [comment]
Is this still relevant? If so please reopen. Sorry for not helping. Best to contact me on Twitter.
